### ISSUE TITLE
Weird unicodes in decompiled source on Linux

### ISSUE THREAD

**Issue by jhrldev** [borisf/classyshark-bytecode-viewer#4]
![Print](https://image.prntscr.com/image/fHKs2K0vSwKEzldhrR5Aog.png)

Environment:
- ClassyShark Bytecode Viewer version: 5.0
- SO: Linux 4.11.9-1-ARCH x86_64 GNU/Linux
- Graphical Interface: Xfce4.12

**Comment by borisf** [comment]
Can you share the problematic class file, please (either here or via Google drive)

**Comment by IRus** [comment]
Same for me.
[Application.class.txt](https://github.com/borisf/classyshark-bytecode-viewer/files/1201302/Application.class.txt)

**Comment by IRus** [comment]
Looks like there are problem with coloring. Maybe procyon generates output with color codes https://unix.stackexchange.com/questions/124407/what-color-codes-can-i-use-in-my-ps1-prompt#124408

**Comment by borisf** [comment]
Weird, on Mac I see the class. Probably an issue with Linux and Java swing, will look deeper

**Comment by ahmedre** [comment]
I have the same problem (on Mac), even with the `Application.class` file that IRus attached above. I am running it from the command line `java -jar classyshark-bytecode-viewer.jar` on Mac (Java 1.8.0_131).

**Comment by borisf** [comment]
Managed to reproduce the bug, happened only via command line. Will investigate

**Comment by borisf** [comment]
Fix is right here - https://github.com/borisf/classyshark-bytecode-viewer/commit/0b0e534fd9ce5946c265be6042cc4033c3442a6e

The reason was bug was redirecting stdout output which causes issues on various terminals. The fix was the proper using of Procyon without the redirect. Will release the version shortly
